sudo: required
services:
  - docker

before install:
  - docker build -t markbdsouza/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true markbdsouza/react-test npm test

after_success:
  - docker build -t markbdsouza/multi-container-client ./client
  - docker build -t markbdsouza/multi-container-nginx ./nginx
  - docker build -t markbdsouza/multi-container-server ./server
  - docker build -t markbdsouza/multi-container-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push markbdsouza/multi-container-client
  - docker push markbdsouza/multi-container-nginx
  - docker push markbdsouza/multi-container-server
  - docker push markbdsouza/multi-container-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-182020159037
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
